#include "Problem0045.h"
#include "Libs\EulerMath.h"


namespace Euler {

    /**
     * Problem: Triangular, pentagonal, and hexagonal
     *
     * Triangle, pentagonal, and hexagonal numbers are generated by the 
     * following formulae:
     *
     *  Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
     *  Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
     *  Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
     *  
     * It can be verified that T285 = P165 = H143 = 40755.
     *
     * Find the next triangle number that is also pentagonal and hexagonal.
     */
    void Problem45::Solve()
    {
        uint64_t result = 0;
		bool bTriangular = false;
		uint64_t j = 286ull; // Since we know it must be superior

		while (!bTriangular)
		{
			// Generate triangular number and apply test for
			// pentagonal and hexagonal numbers
			uint64_t triangleNumber = (j * (j + 1)) >> 1;

			if (EulerLib::IsPentagonalNumber(triangleNumber) &&
				EulerLib::IsHexagonalNumber(triangleNumber))
			{
				result = triangleNumber;
				bTriangular = true;
			}

			++j;
		}

        SetAnswer(result);
    }
}