#include "Problem0002.h"
#include "Libs/FibonacciSequence.h"

namespace Euler {

    /**
     * Problem: Even Fibonacci numbers
     *
     * Each new term in the Fibonacci sequence is generated by adding the previous
     * two terms. By starting with 1 and 2, the first 10 terms will be:
     *
     *                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     *
     * By considering the terms in the Fibonacci sequence whose values do not
     * exceed four million, find the sum of the even-valued terms.
     */
    void Problem2::Solve()
    {
        const uint32_t kLimit = 4000000;

        EulerLib::FibonacciSequence<uint64_t> fibonacci(1, 2);

        uint64_t fibN = 2;
        uint64_t result = 0;

        while (fibN <= kLimit)
        {
            if ((fibN & 0x1) == 0) // Fast % 2
            {
                result += fibN;
            }

            fibN = fibonacci();
        }

        SetAnswer(result);
    }

}